/**
 * PRISMA Flow Diagram Generator
 * Generate PRISMA 2020 flow diagrams for systematic reviews
 *
 * @module PRISMAGenerator
 */

/**
 * Default PRISMA data structure
 */
export const DEFAULT_PRISMA_DATA = {
  identification: {
    database: 0,
    registry: 0,
    other: 0,
    total: 0
  },
  screening: {
    afterDuplicatesRemoved: 0,
    afterTitleAbstract: 0,
    afterFullText: 0
  },
  inclusion: {
    qualitative: 0,
    quantitative: 0
  },
  exclusion: {
    reasons: {},
    total: 0
  }
};

/**
 * Generate PRISMA flow diagram SVG
 * @param {Object} data - PRISMA data
 * @param {Object} options - Generation options
 * @returns {string} SVG string
 */
export function generatePRISMASVG(data, options = {}) {
  const {
    width = 800,
    height = 1000,
    fontSize = 14,
    boxWidth = 200,
    boxHeight = 50,
    boxColor = '#ffffff',
    strokeColor = '#000000',
    arrowColor = '#666666'
  } = options;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">`;

  // Background
  svg += `<rect width="${width}" height="${height}" fill="#ffffff"/>`;

  // Title
  svg += `
    <text x="${width / 2}" y="40" text-anchor="middle" font-size="24" font-weight="bold" font-family="Arial, sans-serif">
      PRISMA 2020 Flow Diagram
    </text>
  `;

  const centerX = width / 2;
  const leftX = centerX - boxWidth / 2;
  let y = 80;

  // Identification section
  y = drawIdentificationSection(svg, data, leftX, y, boxWidth, boxHeight, fontSize, strokeColor);

  // Screening section
  y = drawScreeningSection(svg, data, leftX, y, boxWidth, boxHeight, fontSize, strokeColor, arrowColor);

  // Inclusion section
  y = drawInclusionSection(svg, data, leftX, y, boxWidth, boxHeight, fontSize, strokeColor, arrowColor);

  // Exclusion section (if applicable)
  if (data.exclusion && data.exclusion.total > 0) {
    y = drawExclusionSection(svg, data, leftX, y, boxWidth, boxHeight, fontSize, strokeColor, arrowColor, options.includeReasons);
  }

  // Footer
  svg += `
    <text x="${width / 2}" y="${height - 20}" text-anchor="middle" font-size="10" fill="#666666" font-family="Arial, sans-serif">
      Generated by Living Meta-Analysis
    </text>
  `;

  svg += '</svg>';

  return svg;
}

/**
 * Draw identification section
 */
function drawIdentificationSection(svg, data, x, y, width, height, fontSize, strokeColor) {
  // Databases
  drawBox(svg, x, y, width, height, `Identified through database searching (n = ${data.identification.database})`, fontSize, strokeColor);
  y += height + 30;

  // Registries
  drawBox(svg, x, y, width, height, `Identified through registries (n = ${data.identification.registry})`, fontSize, strokeColor);
  y += height + 30;

  // Other sources
  drawBox(svg, x, y, width, height, `Identified through other methods (n = ${data.identification.other})`, fontSize, strokeColor);
  y += height + 40;

  // Total
  const total = data.identification.total || data.identification.database + data.identification.registry + data.identification.other;
  drawBox(svg, x, y, width, height, `Total records identified (n = ${total})`, fontSize, strokeColor, '#f0f0f0');
  y += height + 40;

  return y;
}

/**
 * Draw screening section
 */
function drawScreeningSection(svg, data, x, y, width, height, fontSize, strokeColor, arrowColor) {
  // After duplicates removed
  drawBox(svg, x, y, width, height, `Records after duplicates removed (n = ${data.screening.afterDuplicatesRemoved})`, fontSize, strokeColor);
  y += height + 30;

  // Arrow with label
  y = drawArrow(svg, x + width / 2, y, x + width / 2, y + 30, arrowColor, 'Screened');
  y += 40;

  // Title/abstract screening
  drawBox(svg, x, y, width, height, `Records screened (title/abstract) (n = ${data.screening.afterDuplicatesRemoved})`, fontSize, strokeColor);
  y += height + 30;

  // After title/abstract
  const excludedTitleAbstract = data.screening.afterDuplicatesRemoved - data.screening.afterTitleAbstract;
  drawBox(svg, x, y, width, height, `Records excluded (title/abstract) (n = ${excludedTitleAbstract})`, fontSize, strokeColor, '#fff0f0');
  y += height + 40;

  // Full-text assessed
  drawBox(svg, x, y, width, height, `Full-text articles assessed for eligibility (n = ${data.screening.afterTitleAbstract})`, fontSize, strokeColor);
  y += height + 30;

  // After full-text
  const excludedFullText = data.screening.afterTitleAbstract - data.screening.afterFullText;
  drawBox(svg, x, y, width, height, `Full-text articles excluded (n = ${excludedFullText})`, fontSize, strokeColor, '#fff0f0');
  y += height + 40;

  return y;
}

/**
 * Draw inclusion section
 */
function drawInclusionSection(svg, data, x, y, width, height, fontSize, strokeColor, arrowColor) {
  // Studies included
  drawBox(svg, x, y, width, height, `Studies included in review (n = ${data.inclusion.qualitative})`, fontSize, strokeColor, '#f0fff0');
  y += height + 30;

  // Quantitative synthesis
  if (data.inclusion.quantitative > 0) {
    drawArrow(svg, x + width / 2, y, x + width / 2, y + 30, arrowColor);
    y += 40;
    drawBox(svg, x, y, width, height, `Studies included in quantitative synthesis (meta-analysis) (n = ${data.inclusion.quantitative})`, fontSize, strokeColor, '#f0f8ff');
    y += height + 40;
  }

  return y;
}

/**
 * Draw exclusion section with reasons
 */
function drawExclusionSection(svg, data, x, y, width, height, fontSize, strokeColor, arrowColor, includeReasons = false) {
  if (!data.exclusion || !data.exclusion.reasons) return y;

  const reasons = data.exclusion.reasons;
  const reasonEntries = Object.entries(reasons);

  if (reasonEntries.length === 0) return y;

  // Draw exclusion reasons
  drawBox(svg, x, y, width, height, `Excluded (full-text) (n = ${data.exclusion.total})`, fontSize, strokeColor, '#fff0f0');
  y += height + 30;

  if (includeReasons) {
    for (const [reason, count] of reasonEntries) {
      drawBox(svg, x, y, width, height, `${reason} (n = ${count})`, fontSize, strokeColor, '#fff5f5');
      y += height + 15;
    }
  }

  return y + 20;
}

/**
 * Draw a box with text
 */
function drawBox(svg, x, y, width, height, text, fontSize, strokeColor, fillColor = '#ffffff') {
  svg += `
    <rect x="${x}" y="${y}" width="${width}" height="${height}"
          fill="${fillColor}" stroke="${strokeColor}" stroke-width="2" rx="5"/>
    <text x="${x + width / 2}" y="${y + height / 2 + fontSize / 3}"
          text-anchor="middle" font-size="${fontSize}" font-family="Arial, sans-serif">
      ${escapeXML(text)}
    </text>
  `;
}

/**
 * Draw an arrow
 */
function drawArrow(svg, x1, y1, x2, y2, color, label = '') {
  // Arrow line
  let svg = `
    <line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"
          stroke="${color}" stroke-width="2" marker-end="url(#arrowhead-${color.replace('#', '')})"/>
  `;

  // Arrow label
  if (label) {
    svg += `
      <text x="${x1 + 20}" y="${y1 + (y2 - y1) / 2}"
            font-size="12" fill="${color}" font-family="Arial, sans-serif">
        ${escapeXML(label)}
      </text>
    `;
  }

  return y2;
}

/**
 * Escape XML special characters
 */
function escapeXML(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Generate PRISMA data from screening workflow
 * @param {Object} screeningData - Screening data
 * @returns {Object} PRISMA data
 */
export function calculatePRISMAData(screeningData) {
  const {
    totalRecords = 0,
    duplicates = 0,
    excludedTitleAbstract = 0,
    excludedFullText = 0,
    exclusionReasons = {},
    includedQualitative = 0,
    includedQuantitative = 0
  } = screeningData;

  return {
    identification: {
      database: Math.floor(totalRecords * 0.8),
      registry: Math.floor(totalRecords * 0.15),
      other: totalRecords - Math.floor(totalRecords * 0.8) - Math.floor(totalRecords * 0.15),
      total: totalRecords
    },
    screening: {
      afterDuplicatesRemoved: totalRecords - duplicates,
      afterTitleAbstract: totalRecords - duplicates - excludedTitleAbstract,
      afterFullText: includedQualitative
    },
    inclusion: {
      qualitative: includedQualitative,
      quantitative: includedQuantitative
    },
    exclusion: {
      reasons: exclusionReasons,
      total: excludedFullText
    }
  };
}

/**
 * Export PRISMA diagram as PNG
 * @param {Object} data - PRISMA data
 * @param {Object} options - Generation options
 * @returns {Promise<Blob>} PNG blob
 */
export async function exportPRISMAAsPNG(data, options = {}) {
  const svg = generatePRISMASVG(data, options);

  return new Promise((resolve, reject) => {
    const img = new Image();
    const svgBlob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);

    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = options.width || 800;
      canvas.height = options.height || 1000;

      const ctx = canvas.getContext('2d');
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0);

      canvas.toBlob(blob => {
        URL.revokeObjectURL(url);
        resolve(blob);
      }, 'image/png');
    };

    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to load SVG'));
    };

    img.src = url;
  });
}

/**
 * Download PRISMA diagram
 * @param {Object} data - PRISMA data
 * @param {string} format - Format ('svg' or 'png')
 * @param {Object} options - Generation options
 */
export async function downloadPRISMA(data, format = 'svg', options = {}) {
  const filename = options.filename || `prisma_diagram_${Date.now()}`;

  if (format === 'svg') {
    const svg = generatePRISMASVG(data, options);
    const blob = new Blob([svg], { type: 'image/svg+xml' });
    downloadBlob(blob, `${filename}.svg`);
  } else if (format === 'png') {
    try {
      const blob = await exportPRISMAAsPNG(data, options);
      downloadBlob(blob, `${filename}.png`);
    } catch (error) {
      console.error('Failed to export PNG:', error);
      throw error;
    }
  }
}

/**
 * Helper to download a blob
 */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Create interactive PRISMA diagram in DOM
 * @param {HTMLElement} container - Container element
 * @param {Object} data - PRISMA data
 * @param {Object} options - Options
 */
export function renderPRISMAInDOM(container, data, options = {}) {
  const svg = generatePRISMASVG(data, options);

  container.innerHTML = `
    <div class="prisma-diagram-container">
      ${svg}
      <div class="prisma-controls mt-4 flex justify-center space-x-4">
        <button class="btn-primary" data-action="download-svg">
          Download SVG
        </button>
        <button class="btn-secondary" data-action="download-png">
          Download PNG
        </button>
      </div>
    </div>
  `;

  // Add event listeners
  const svgBtn = container.querySelector('[data-action="download-svg"]');
  const pngBtn = container.querySelector('[data-action="download-png"]');

  svgBtn?.addEventListener('click', () => {
    downloadPRISMA(data, 'svg', options);
  });

  pngBtn?.addEventListener('click', () => {
    downloadPRISMA(data, 'png', options);
  });
}

export default {
  generatePRISMASVG,
  exportPRISMAAsPNG,
  downloadPRISMA,
  calculatePRISMAData,
  renderPRISMAInDOM,
  DEFAULT_PRISMA_DATA
};
